version: 2

project_name: gh-app-auth

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-app-auth
    main: .
    binary: gh-app-auth
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - gh-app-auth
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats: [binary]

checksum:
  name_template: "checksums.txt"
